### PR TITLE
Add ActivityFeed to record activity feed events

### PR DESCRIPTION
**Pull request by madprime**

### CODE REVIEW

**Comment by gedankenstuecke** [comment]
I still don't fully understand why all the additions don't show up in the test coverage. @beaugunderson can you help me out to see what's going on?

**Comment by beaugunderson** [comment]
looks like something changed in the codecov config? i'll see if it's an easy fix

screenshot

**Comment by gedankenstuecke** [comment]
Thanks! 👍

**Comment by beaugunderson** [comment]
also i'm no longer an org owner so one of you should visit codecov and go through the upgrade flow:

screenshot

**Comment by beaugunderson** [comment]
i don't see an issue with the yaml so it may just be an issue of this repo being on the legacy service and not knowing how to handle pull requests anymore... @gedankenstuecke upgrade and see if that fixes it :)

**Comment by gedankenstuecke** [comment]
Ok, I ran the update and added `OpenHumans/open-humans` to their list. I can't see any changes so far on their end though.

**Pull request merged**
