### PR TITLE
Add filters on is_active User status

### PR DESCRIPTION
**Pull request by madprime**
...thereby enabling account suspensions.

### CODE REVIEW

**Comment by madprime** [comment]
@gedankenstuecke No, it returns an authentication error, as if they have the wrong password. And a request for a password reset email seems to fail silently. (No error reported, no email sent?) I think this is OK but could definitely be more user-friendly.

**Comment by gedankenstuecke** [comment]
Okay, sounds good to me. Maybe should add to the suspension email that they need to email us as well if they want us to fully delete the account then.

**Comment by madprime** [comment]
I'll merge & let you create new issues or edit email as you see fit :)

**Comment by gedankenstuecke** [comment]
Ok, just added to the suspension email to make the consequences more clear.

**Pull request merged**
